Conflicteventform
digimonkt/tacticulture-frontend pull request #22
Opened 2023-06-05 13:58 UTC by RohitDigimonk

2023-06-06 06:08 UTC, muddledluck requested changes

2023-06-06 06:08 UTC, muddledluck commented on src/pages/instructor/manage-event/index.tsx
> +              {eventData?.results?.map((Data) => (
`Data` should be `data`

2023-06-06 06:08 UTC, muddledluck commented on src/redux/reducers/user.ts
> +  console.log(res, "res");
I think no need of `console.log` here

2023-06-07 06:04 UTC, muddledluck approved these changes

2023-06-07 06:04 UTC, merged

2023-06-07 06:16 UTC, RohitDigimonk commented
all conflict resolved