registration-setup
digimonkt/tacticulture-frontend pull request #7
Opened 2023-05-10 05:21 UTC by alisarfaraj

2023-05-19 07:04 UTC, muddledluck requested changes

2023-05-19 07:04 UTC, muddledluck commented on src/pages/setup-profile/index.tsx
> +        default_profile: role,
use `camelCase`

2023-05-19 07:04 UTC, muddledluck commented on src/redux/reducers/userRole.ts
> +  userRole: USER_ROLES | null;
if no need then remove this file

2023-05-19 07:04 UTC, muddledluck commented on src/redux/store/store.ts
> +    userReducer,
follow same name conventations

2023-05-19 07:04 UTC, muddledluck commented on src/utils/interfaces.ts
> +  user_roles: USER_ROLES;
use `camelCase`

2023-05-19 07:21 UTC, merged

2023-05-22 07:18 UTC, 0422-shiv commented on src/pages/setup-profile/index.tsx
> +        default_profile: role,
It's backend fields so no need to change camel case

2023-05-22 07:28 UTC, 0422-shiv commented on src/redux/reducers/userRole.ts
> +  userRole: USER_ROLES | null;
No need to remove this file

2023-05-23 05:40 UTC, alisarfaraj commented on src/component/lightBoxes/imageCropper.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
couldn't remove it